### PR TITLE
render markdown in user description

### PR DESCRIPTION
**Pull request by willemarcel**
captura de tela de 2017-08-25 17-55-58

I would like to disallow images to be rendered. I tested to add {disallowedTypes: ['Image']} to the markdown renderer, but it didn't work.

### CODE REVIEW

**Comment by kepta** [comment]
@willemarcel we are already using a library called [showdown](https://github.com/showdownjs/showdown) over [here](https://github.com/mapbox/osmcha-frontend/blob/master/src/views/about.js#L3) to parse the about.md form GitHub. 
I guess it would be great if we could reuse that.

**Comment by willemarcel** [comment]
Yes, @kepta! I'll change it to use `showdown`. Thanks!

**Comment by willemarcel** [comment]
@kepta I've replaced `commonmark-react-renderer` by `showdown` lib

**Comment by kepta** [comment]
@willemarcel looks good to me.

**Comment by tridip1931** [comment]
@willemarcel Thanks for this enhancement. All looks good, merging this.

**Pull request merged**
