### PR TITLE
add a news alert modal to inform the user of changes in OSMCha software

### PR DESCRIPTION
**Pull request by willemarcel**
The first news is set to inform the user that we will post comments on the reviewed changeset pages

captura de tela de 2017-12-15 17-31-27

The alert is shown only three times (if the user closes it, it will appear again only if the user refresh the page). If the user do the logout or clear the local storage, the count will restart from zero.

@jinalfoflia @batpad  could you review the text?
@kepta do you think the current implementation is good? Some improvement idea?

Related to https://github.com/willemarcel/osmcha-django/issues/128

### CODE REVIEW

**Comment by govvin** [comment]
It would be really nice if it would be possible for the reviewer to add text, to elaborate on their review, within OsmCha.

Right now, they could add a separate comment.

image

**Comment by tridip1931** [comment]
👋 @govvin that is a great suggestion. 
Did you look at the widget panel. OSMCha already fetches comments from OSM.

screen shot 2018-01-10 at 10 36 56

**Comment by govvin** [comment]
@tridip1931 , yes, I have.

What I mean is, instead of the long-ish blurb above, you could have a reviewer's comment there instead.

**Comment by tridip1931** [comment]
aah, I get it now. 👍

**Comment by willemarcel** [comment]
> It would be really nice if it would be possible for the reviewer to add text, to elaborate on their review, within OsmCha.

Hi @govvin! I have thought about this, but we decided to start with the more basic behaviour and improve later depending on the response of the community. Could you open a new issue with your suggestion? That way the community can easily find the topic and contribute to the discussion. Thank you!!

**Pull request merged**
