### PR TITLE
0.58.0 release

### PR DESCRIPTION
**Pull request by willemarcel**
* Exclude changesets newer than 5 minutes from query results
* Change position of status notification
* Show unverified teams and add string to distinct the verified ones on the filters page

### CODE REVIEW

**Comment by mmd-osm** [comment]
> Exclude changesets newer than 5 minutes from query results

Why isn't the fix in changeset-map deployed to production instead?

**Comment by willemarcel** [comment]
@mmd-osm I'm having some issues with changeset-map, caused probably by some outdated dependencies, so I'm not succeeding on building it and the installation of newer versions on osmcha-frontend is failing. I asked @kepta to help me with it, but he is very busy this week. I hope next week we can have some news on it.

**Comment by willemarcel** [comment]
@mmd-osm good news! @batpad gave me a solution to that problem. I'll test it later and update changeset-map on this release

**Comment by willemarcel** [comment]
@mmd-osm I finally could push to production the updates on changeset-map regarding the overpass api. Thank you!

**Pull request merged**
