### PR TITLE
Save filter

### PR DESCRIPTION
**Pull request by kepta**
Continuing from #198 

Original comment by @willemarcel 
—�—�—�—�—�—�—�—�—�-
> I made some changes related to what I proposed in https://github.com/mapbox/osmcha-frontend/issues/167

>osm changeset analyzer 1

>It has some bugs yet... I would be happy if someone can help:
>- [ ] when you load a saved filter, it's name is exhibited correctly, but, in the save form input, the name is empty. If you click on the `X` to close the filter and click on the `Filter` button, and finally in the `Save`, it will load the name correctly.
osm changeset analyzer

>- [ ] After updating a filter, the request is sent and the update occurs perfectly in the backend, but the frontend reload the page to the state before the update (load a filter, modify and save it to reproduce. If you press F5 you will see that the filter was updated).

### CODE REVIEW

**Comment by kepta** [comment]
@willemarcel the reason why you are getting error is that you are calling the redux saga directly [here](https://github.com/mapbox/osmcha-frontend/pull/199/files#diff-11a78cb1fe9a5f609f9b63fb5faaf870R167) . 

You need to dispatch an action from your react component like [this]
 https://github.com/mapbox/osmcha-frontend/blob/3ee3a5b8759929d4c89cea7b992732e1e120ed0e/src/views/navbar_sidebar.js#L56 which in turn is an action defined as action. https://github.com/mapbox/osmcha-frontend/blob/3ee3a5b8759929d4c89cea7b992732e1e120ed0e/src/store/auth_actions.js#L36-L37

so basically these action functions are just a convention to actually make an object, in this case if you console.log that 
```Javascript
console.log(action(AUTH.getFinalToken, { oauth_verifier })); 
// {
//   type: AUTH.getFinalToken,
//   oauth_verifier: "9d4c89cea7b992732e1e120ed0"
// }
```
After this you need to make sure your saga is listening for actions, by registering it 
https://github.com/mapbox/osmcha-frontend/blob/3ee3a5b8759929d4c89cea7b992732e1e120ed0e/src/store/filters_actions.js#L65-L70
In the above example `Line 68` `watchFilters` will takeLatest action `FILTERS.apply` and call `applyFilterSaga`. So you would want to do something similar for your saga aswell.

**Comment by willemarcel** [comment]
Hi @kepta 

I fixed the parts of the code you mentioned, but I'm yet having one error when saving:

`TypeError: _this.props.aoi is undefined`

```
getAOIName = () => {
  151 |   if (this.props.loading) return '';
> 152 |   return this.props.aoi.getIn(['properties', 'name'], NEW_AOI);
  153 | };
```
Do you have some idea why this is happening? I guess it is related to the fact that as the request is asynchronous, so the code tries to get the variable before it's available.

Thank you for the help!

**Comment by kepta** [comment]
@willemarcel could you tell me how do I reproduce the bug.

**Comment by kepta** [comment]
@willemarcel I think I have made it work. I would suggest you break down all the AOI redux/store into its own folder. I would make it something like `store/aoi_actions.js` and `store/aoi_reducer.js`. This way it would reduce the noise and complexity 👍 .

**Comment by willemarcel** [comment]
@kepta Thank you very much for the help!! I achieved to put the aoi actions and reducers in separate files and I converted the `createAOI` to use `SAGA`, It has only one bug: after create an AOI, it redirects to `aoi=undefined`.

Could you take a look on it?

**Comment by willemarcel** [comment]
Hi @kepta 

I succeeded to solve the last bug. I believe now it's ready to review and merge!

**Pull request merged**
